language: c

sudo: false

addons:
  apt:
    packages:
    - haskell-platform
    - equivs
    - python

env:
  global:
    - PATH=$PATH:$HOME/.cabal/bin
    - secure: "cZPwfB7g61JhnmFFzVn86u9j3RqIfLIzyodnM8m14GPKtXCxPltGNOMORjynmD5BqPh0mtwrdFZ0r1jb1WplYXbDMitsDyadeN5tn/Ka6F/bqCM3OiOE1TZv+HDVL1XiUzArW4f0gFLaUti576pf77ciuhaICbdYQPeLoS17QhDBBrTrGfih8QeWgnn82gnwKwRqBjmLfNe5nUZnQuvmyZTA/sCIjSnSkgT7Hso/KPDxGWSkP/3sUOPfapOMupRLkDdTsM8uLTE5JueNySDp/rdszazZt5eqOijYwAMGrHhVfE/mPd/vV8YL/S1JeZmax7tm0dmrIz9LIO7iMOWGX9GEimoudjrZJeuPiku62L4XNbBee8YF0yD7SqKNpIRgU3yX0eJxKuC4VHoiTPFgjJ5SzoORV23Qg2bjN+6cZCC15buIVgDCy3Vf0v0Hn7zAeDXTtRVkuVEal138JVIQ5gBhKDQiJ97OenMaEGgj8kTr7zqfcX8cQeFNHOftwzJ2xdjDeZA0rcjNvcnzp6hBeJz5MGiqWbDHv6cWraGMng/1FWszVpffti/lnoWMrlJn25nEgZBxBre7nzJDKAoqzzoWThnYU+LxGRPaZT/2MpsGy4T04UsqXedmoS/AZmTIE9S8YUbLa9JkMYsYqqQslrgAjrH5TJMFStXrF3nRjio="
  matrix:
    - TARGET=pandoc
    - TARGET=texlive

before_install:
  - export COMMIT_TARGET="$(git log --format=%B --no-merges -n 1 | grep -E "\[build .+\]" | sed 's/.*\[build \(.*\)\].*/\1/')"
  - "if [ ! -z $COMMIT_TARGET ]; then if [ $COMMIT_TARGET != $TARGET ]; then export TARGET=''; fi; fi"

install:
  - "[ -z $TRAVIS_TAG ] && exit 0 || true"
  - ./install

script:
  - "[ -z $TRAVIS_TAG ] || ./build"

cache:
  directories:
  - $HOME/.cabal

before_deploy:
  - "[ -z $TRAVIS_TAG ] || [ -z $TARGET ] || curl -s https://api.github.com/repos/yihui/ubuntu-bin/releases/latest | python delete.py $TARGET"


deploy:
  provider: releases
  api-key:
    secure: "XdUtAjebTliMdSYI3UYevVh5P8rT8n+Y5cFPOhsV3QI16ehdMgUxd430lqHUEqRa9jCIuioHVh6dPV8pyBo8mnF61IYLeMkHvi/aPNcnL2GCNGx6Dsg5mtn1N3HvrUrA8aD17MuEtps5zzlp37FAk8MTBA/J+/IruVOeoCmFokUvqnRdg7uMSb6EExV0VLQVnyoUO9hHBF+LXFosoCjIA8T2hzCgPyFBmZd/00i2LtYd7zfFPOhIVmKyh5m7V8aH96YElCq5e1JLYtBfZHAHo+OjLaw5w74Xs1uKbxfgosTrhIbMDqNfLN8e2ZURfrFCWkXyLtqrLcbKVW21z82C/7bCrrRNei/HTFbHWt0t7uHKyIUzXNLMnB24DeyzNV7BqG7CdPtz7xogm9KvVpVNMLZ3S7VfmLn3FaMN5DOkKNBX8JuQtA8oEjIMDWMsisLjGHxVSZ2etq2O4KdKV+9GwKyDVnzJBsnKWgqeFlhswuBEy5zzySxJIX8UptVFjnKSnNYnAxHxMRUaaEJ7EgbwX7yjiOpMuKmMUyuALyu0mtK8FvfXQff2eGKIL9wDSg7nLuEM0ar8ulWTK0Di79hhvw8ysNneKKWbVFOQafdzKBYCKBPe7zCCzrmzuwR2lFgJaShUlxS/PVRvcStY94w+hglQAeZAGt65qfl+IvHtXS4="
  file:
    - pandoc*
    - texlive*
    - R-*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: $TARGET != ""
